/** Enterprise identity, session, resource-policy, and audit persistence. */

export { ENTERPRISE_IDENTITY_SCHEMA_VERSION, migrateEnterpriseIdentity } from './schema.ts'
export {
  classifyPrivacyForScope,
  inspectEnterpriseMemory,
  memorySourceDigest,
  type EnterpriseMemoryInspection,
  type EnterpriseMemoryPrivacyFinding,
  type EnterpriseMemoryScopeDecision,
} from './memory-policy.ts'
export {
  EnterpriseIdentityRepository,
  type IdentityAwaitable,
  type EnterpriseIdentityStore,
  sessionTokenHash,
  type AuditQuery,
  type EnterpriseAuditRecord,
  type EnterpriseManagedAsset,
  type EnterpriseOrganization,
  type EnterprisePrincipalView,
  type EnterpriseResourcePolicy,
  type EnterpriseUserInput,
  type EnterpriseUserView,
  type CreateEnterpriseUserOptions,
  type CreateEnterpriseOrganizationInput,
  type UpdateEnterpriseUserProfileInput,
  type EnterpriseDepartment,
  type SaveEnterpriseDepartmentInput,
  type SetUserDepartmentsInput,
  type EnterpriseWorkspaceGrant,
  type SaveEnterpriseWorkspaceGrantInput,
  type EnterpriseMemoryEntry,
  type MemoryKind,
  type MemoryListFilterPlan,
  MEMORY_KINDS,
  MEMORY_SCOPES,
  type MemoryScope,
  planMemoryListFilters,
  type ProposeEnterpriseMemoryInput,
  validatePrivateMemoryInput,
  type ValidatedPrivateMemory,
  type WritePrivateMemoryInput,
  type ReviewEnterpriseMemoryInput,
  type ExternalIdentityBinding,
  type RepositoryOptions,
} from './repository.ts'
export {
  attachSurfaceSession,
  bindSticky,
  claimInbox,
  createEmployee,
  enqueueInbox,
  ensureSurface,
  enumColumn,
  failInboxItem,
  getEmployee,
  listEmployees,
  resolveSticky,
  surfaceBySession,
  updateEmployeeState,
  type EmployeeAccountRow,
  type InboxRow,
  type SurfaceRow,
} from './employee-store.ts'
