/** Enterprise identity, session, resource-policy, and audit persistence. */

export { ENTERPRISE_IDENTITY_SCHEMA_VERSION, migrateEnterpriseIdentity } from './schema.ts'
export {
  classifyPrivacyForScope,
  inspectEnterpriseMemory,
  memorySourceDigest,
  type EnterpriseMemoryInspection,
  type EnterpriseMemoryPrivacyFinding,
  type EnterpriseMemoryScopeDecision,
} from './memory-policy.ts'
export {
  EnterpriseIdentityRepository,
  type IdentityAwaitable,
  type EnterpriseIdentityStore,
  type EnterpriseSessionAccessFacts,
  sessionTokenHash,
  type AuditQuery,
  type EnterpriseAuditRecord,
  type EnterpriseManagedAsset,
  type EnterpriseOrganization,
  type EnterprisePrincipalView,
  type EnterpriseResourcePolicy,
  type EnterpriseUserInput,
  type EnterpriseUserView,
  type CreateEnterpriseUserOptions,
  type CreateEnterpriseOrganizationInput,
  type UpdateEnterpriseUserProfileInput,
  type EnterpriseDepartment,
  type SaveEnterpriseDepartmentInput,
  type SetUserDepartmentsInput,
  type EnterpriseWorkspaceGrant,
  type SaveEnterpriseWorkspaceGrantInput,
  type EnterpriseMemoryEntry,
  type MemoryKind,
  type MemoryListFilterPlan,
  MEMORY_KINDS,
  MEMORY_SCOPES,
  type MemoryScope,
  planMemoryListFilters,
  type MemoryImportanceUpdate,
  type ProposeEnterpriseMemoryInput,
  validateMemoryImportanceUpdates,
  validatePrivateMemoryInput,
  type ValidatedPrivateMemory,
  type WritePrivateMemoryInput,
  type ReviewEnterpriseMemoryInput,
  type ExternalIdentityBinding,
  type RepositoryOptions,
} from './repository.ts'
export {
  attachGroupSurfaceSession,
  attachSurfaceSession,
  attachTopicSession,
  bindSticky,
  channelSurfaceByExternalKey,
  channelTopic,
  claimInbox,
  createEmployee,
  dutyRoster,
  enqueueInbox,
  ensureChannelSurface,
  ensureGroupSurface,
  ensureSurface,
  ensureTopic,
  employeeByHomeWorkspacePath,
  enumColumn,
  failInboxItem,
  getEmployee,
  groupSessionBinding,
  groupSurfaceSession,
  listEmployees,
  listSurfaces,
  resolveSticky,
  setDutyRoster,
  settleTopic,
  setSurfaceMembers,
  surfaceById,
  surfaceBySession,
  surfaceMembers,
  topicBySession,
  topicsBySurface,
  updateEmployeeState,
  type ChannelSurfaceRow,
  type ChannelTopicRow,
  type EmployeeAccountRow,
  type EnsureChannelSurfaceRow,
  type EnsureGroupSurfaceRow,
  type EnsureTopicRow,
  type GroupSurfaceRow,
  type InboxRow,
  type SurfaceMemberInput,
  type SurfaceMemberRow,
  type SurfaceRow,
} from './employee-store.ts'
